apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vocalmarket

resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - enthusiast-api.yaml
  - whisper.yaml
  - ai-orchestrator.yaml
  - voice.yaml
  - api-gateway.yaml
  - otel-collector.yaml
  - hpa.yaml
